// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtK6IdTndVJFzLRyhHxRXhCXkNSCF2u54',
    appId: '1:394188423373:web:d2cde48674778ee0472984',
    messagingSenderId: '394188423373',
    projectId: 'aptech-e-project-flutter',
    authDomain: 'aptech-e-project-flutter.firebaseapp.com',
    storageBucket: 'aptech-e-project-flutter.appspot.com',
    measurementId: 'G-6T9CSWE71V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgKuAR5VADuTWMGkeRmLf-QL0zwBk_X4c',
    appId: '1:394188423373:android:609aed3c7e50ebe4472984',
    messagingSenderId: '394188423373',
    projectId: 'aptech-e-project-flutter',
    storageBucket: 'aptech-e-project-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ3OkqlDTJLvAa8AJZ1jwX5kZr8x2Kj_o',
    appId: '1:394188423373:ios:87d614f6e3019003472984',
    messagingSenderId: '394188423373',
    projectId: 'aptech-e-project-flutter',
    storageBucket: 'aptech-e-project-flutter.appspot.com',
    iosBundleId: 'com.example.aptechEProjectFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ3OkqlDTJLvAa8AJZ1jwX5kZr8x2Kj_o',
    appId: '1:394188423373:ios:87d614f6e3019003472984',
    messagingSenderId: '394188423373',
    projectId: 'aptech-e-project-flutter',
    storageBucket: 'aptech-e-project-flutter.appspot.com',
    iosBundleId: 'com.example.aptechEProjectFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtK6IdTndVJFzLRyhHxRXhCXkNSCF2u54',
    appId: '1:394188423373:web:b7aabf1a692e4d6a472984',
    messagingSenderId: '394188423373',
    projectId: 'aptech-e-project-flutter',
    authDomain: 'aptech-e-project-flutter.firebaseapp.com',
    storageBucket: 'aptech-e-project-flutter.appspot.com',
    measurementId: 'G-JRTEN2Q9ZK',
  );
}
